name: build-android
on: [push]

jobs:
  build-android:
    name: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Android SDK 35.0.0
        uses: android-actions/setup-android@v3

      - name: Install Android SDK build tools
        run: |
          sdkmanager "build-tools;35.0.0"
          echo "$ANDROID_SDK_ROOT/build-tools/35.0.0" >> $GITHUB_PATH

      - name: Get keystore
        run: |
          mkdir ~/.keystore 
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > ~/.keystore/keystore.jks

      - name: Build HTML assets for capacitor
        run: npm run build-cap-html

      - name: Synchronize capacitor
        run: |
          npx cap telemetry off
          npx cap sync

      - name: Build APK
        run: |
          cd android/app
          ../gradlew assembleRelease

      - name: Sign APK
        run: |
          apksigner sign --ks ~/.keystore/keystore.jks --ks-pass "pass:${{secrets.ANDROID_KEYSTOREPASS}}" --ks-key-alias "${{secrets.ANDROID_KEYSTOREALIAS}}" --key-pass "pass:${{secrets.ANDROID_KEYSTOREALIASPASS}}" --alignment-preserved --in android/app/build/outputs/apk/release/app-release-unsigned.apk --out android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Rename outputs
        run: |
          sha_short=$(git rev-parse --short HEAD)
          mv android/app/build/outputs/apk/release/app-release-unsigned.apk tessel-${sha_short}-unsigned.apk
          if [[ -f android/app/build/outputs/apk/release/app-release-signed.apk ]] ; then
            mv android/app/build/outputs/apk/release/app-release-signed.apk tessel-${sha_short}.apk
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android package
          path: tessel-*.apk

  make-release:
    name: make-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-android
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Download Android artifacts
        uses: actions/download-artifact@v5

      - name: Copy Changelog from metadata
        run: |
          versionCode=$( grep versionCode android/app/build.gradle | grep -ohE "[0-9]+" )
          touch ${{ github.workspace }}-CHANGELOG.txt
          if [[ -f metadata/en-US/changelogs/${versionCode}.txt ]] ; then
            cat metadata/en-US/changelogs/${versionCode}.txt >> ${{ github.workspace }}-CHANGELOG.txt
          fi

      - name: Rename APK to include version
        run: |
          sha_short=$(git rev-parse --short HEAD)
          mv tessel-${sha_short}.apk tessel-${{ github.ref_name }}.apk
          mv tessel-${sha_short}-unsigned.apk tessel-${{ github.ref_name }}-unsigned.apk

      - name: Make draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            tessel-${{ github.ref_name }}.apk
            tessel-${{ github.ref_name }}-unsigned.apk
          generate_release_notes: true
          body_path: ${{ github.workspace }}-CHANGELOG.txt
